# config/routes/easy_admin.yaml
easy_admin:
    site_name: 'CleberApp'
    design:
        brand_color: '#1ABC9C'
    show:
        title: '%%entity_label%% (%%entity_id%%)'
    list:
        title: '%%entity_label%%'
        actions:
        - { name: edit, icon: pencil, label: ''}
        - { name: show, icon: info-circle, label: ''}
    entities:
        
        Clientes:
            class: App\Entity\Persona
            search: [nombre, apellido, documento, email]
            list:   
                fields:
                    - id
                    - {property: apellido, label: Apellido/RazonSocial}
                    - nombre
                    - documento
                    - {property: gremio,  label: es gremio?}
        Productos:
            class: App\Entity\Producto
            list:
                 title: '<strong>Lista</strong> de productos nuevos'
        Ordenes:
            class: App\Entity\Orden
            list:
                actions:
                    - {name: edit, icon: pencil, label: ''}
                    - {name: show, icon: info-circle, lable: ''}
        Tipodetrabajo:
            class: App\Entity\Tipodetrabajo
        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

